#!/bin/sh

xgettext --language=Python --keyword=_ --output=mintmenu.pot usr/share/linuxmint/mintMenu/mintMenu.py \
#usr/share/linuxmint/mintMenu/mintRemove.py \
usr/share/linuxmint/mintMenu/mintMenuConfig.py \
usr/share/linuxmint/mintMenu/keybinding.py \
usr/share/linuxmint/mintMenu/plugins/recent.py \
usr/share/linuxmint/mintMenu/plugins/applications.py \
usr/share/linuxmint/mintMenu/plugins/system_management.py \
usr/share/linuxmint/mintMenu/plugins/places.py

