.TH MINTMENU 1 "" ""
.SH NAME
mintMenu \- advanced MATE menu
.SH SYNOPSIS
.B mintmenu \fR[option]
.SH DESCRIPTION
mintMenu is one of the most advanced menus under Linux.
It supports filtering, favorites, easy\-uninstallation, autosession, and many other features.
.SH OPTIONS
.TP
.B [\-\-]help\fR,\fB [\-]h\fR,\fB [\-]?
Display command line options.
.TP
.B [\-\-]clean\fR,\fB [\-\-]clear\fR,\fB [\-\-]reset
Restore the mintMenu settings to default by deleting the settings file (\fI~/.linuxmint/mintMenu\fR).
